database:
  driver: org.h2.Driver
  url: jdbc:h2:tcp://localhost/~/test
  properties:
    hibernate.connection.username: sa
    hibernate.connection.password:
    hibernate.hbm2ddl.auto: update
    hibernate.default_schema: INFORMATION_SCHEMA
http:
  port: 8081
