drop table BigDepartment if exists;
drop table ClinicRegister if exists;
drop table ClinicRegisterCategory if exists;
drop table ClinicRegisterType if exists;
drop table Department if exists;
drop sequence hibernate_sequence if exists;

create table BigDepartment (id bigint generated by default as identity, name varchar(255), primary key (id));
create table ClinicRegister (id bigint not null, left integer not null, period varchar(255), validOn timestamp, scheduled integer not null, stopStatus boolean not null, clinicRegisterType_id bigint, primary key (id));
create table ClinicRegisterCategory (id bigint generated by default as identity, name varchar(255), primary key (id));
create table ClinicRegisterType (id bigint generated by default as identity, digitCode varchar(255), name varchar(255), pingyinCode varchar(255), type varchar(255), clinicRegisterCategory_id bigint, department_id bigint, primary key (id));
create table Department (id bigint generated by default as identity, name varchar(255), bigDepartment_id bigint, primary key (id));

alter table ClinicRegister add constraint FK_CLINICREGISTER_CLINICREGISTERTYPE foreign key (clinicRegisterType_id) references ClinicRegisterType;
alter table ClinicRegisterType add constraint FK_CLINICREGISTERTYPE_DEPARTMENT foreign key (department_id) references Department;
alter table ClinicRegisterType add constraint FK_CLINICREGISTERTYPE_CLINICREGISTERCATEGORY foreign key (clinicRegisterCategory_id) references ClinicRegisterCategory;
alter table Department add constraint FK_DEPARTMENT_BIGDEPARTMENT foreign key (bigDepartment_id) references BigDepartment;
create sequence hibernate_sequence;
